# Generated by Django 4.2.7 on 2025-11-25 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва країни')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код країни')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Довгота')),
            ],
            options={
                'verbose_name': 'Країна',
                'verbose_name_plural': 'Країни',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата відвідування')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='travel_tracker.country', verbose_name='Країна')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Відвідування',
                'verbose_name_plural': 'Відвідування',
                'ordering': ['-visited_at'],
                'unique_together': {('user', 'country')},
            },
        ),
    ]
